CREATE TABLE IF NOT EXISTS working_day_overrides (
  id INT NOT NULL AUTO_INCREMENT,
  day DATE NOT NULL,
  is_working_day TINYINT(1) NOT NULL,
  note VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_working_day_overrides_day (day)
) ENGINE=InnoDB;
